In [2]:
import numpy as np
ary = np.random.randn(25)
ary

array([ 1.57545317, -0.34828508, -0.13315084,  1.15752436, -0.0286181 ,
       -0.80268194,  0.24961602, -0.62082876,  1.77024241, -0.78207246,
       -1.80046877, -0.20083224, -2.33792908,  1.05578655,  0.73019173,
        0.80584227,  1.39372805, -0.10412798, -1.38033577,  0.63577754,
       -1.28649031, -1.42324714,  2.27816871, -0.49595717,  0.09310593])

In [10]:
ary = np.arange(30)
print(ary)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [11]:
mean_arry = np.mean(ary)
print(mean_arry)

14.5


In [14]:
ary = np.arange(1,101).reshape(10,10)
ary

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [16]:
ary.max()

100

In [17]:
ary.min()

1

In [19]:
f = np.array([1,2])
g = np.array([4,5])
dot = np.dot(f,g)
dot

14

In [20]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

res = np.concatenate([x,y],axis=0)
res

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
a = np.array([1,2,3,2,3,4,3,4,5,6])

b = np.array([7,2,10,2,7,4,9,4,9,8])

res = np.intersect1d(a,b)
res

array([2, 4])

In [26]:
arr = np.array([10,5,8,4,7,2,3,1])
np.sort(arr)

array([ 1,  2,  3,  4,  5,  7,  8, 10])